### ISSUE TITLE
Loading Hunyuan CKPT Out of Memory

### ISSUE THREAD

**Issue by Aristo23333** [a-r-r-o-w/finetrainers#142]
Hi author! 
Thanks for providing your CKPT for Hunyuan LoRA finetrainers.

But when I am trying to load your CKPT, I get OOM in two 80GB H800s. 
In train.py: trainer.prepare_trainable_parameters.
self.transformer.to(self.state.accelerator.device, dtype=weight_dtype). 
I find you mention 60G is enough for lora training in README.md, could you give me some advice?

My bash is as followed: Thank you
```
export WANDB_MODE="offline"
export NCCL_P2P_DISABLE=1
export TORCH_NCCL_ENABLE_MONITORING=0
export FINETRAINERS_LOG_LEVEL=DEBUG
# export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
# export CUDA_VISIBLE_DEVICES="7"
GPU_IDS="6,7"

DATA_ROOT=""
CAPTION_COLUMN=""
VIDEO_COLUMN=""
OUTPUT_DIR=""

# Model arguments
model_cmd="--model_name hunyuan_video \
  --pretrained_model_name_or_path /finetrainers/CKPT/HunyuanVideo"

# Dataset arguments
dataset_cmd="--data_root $DATA_ROOT \
  --video_column $VIDEO_COLUMN \
  --caption_column $CAPTION_COLUMN \
  --id_token afkx \
  --video_resolution_buckets 17x512x768 49x512x768 61x512x768 129x512x768 \
  --caption_dropout_p 0.05"

# Dataloader arguments
dataloader_cmd="--dataloader_num_workers 0"

# Diffusion arguments
diffusion_cmd=""

# Training arguments
training_cmd="--training_type lora \
  --seed 42 \
  --mixed_precision bf16 \
  --batch_size 1 \
  --train_steps 500 \
  --rank 128 \
  --lora_alpha 128 \
  --target_modules to_q to_k to_v to_out.0 \
  --gradient_accumulation_steps 1 \
  --gradient_checkpointing \
  --checkpointing_steps 500 \
  --checkpointing_limit 2 \
  --enable_slicing \
  --enable_tiling"

# Optimizer arguments
optimizer_cmd="--optimizer adamw \
  --lr 2e-5 \
  --lr_scheduler constant_with_warmup \
  --lr_warmup_steps 100 \
  --lr_num_cycles 1 \
  --beta1 0.9 \
  --beta2 0.95 \
  --weight_decay 1e-4 \
  --epsilon 1e-8 \
  --max_grad_norm 1.0"

# Validation arguments
validation_cmd="--validation_prompts \"afkx A baker carefully cuts a green bell pepper cake on a white plate against a bright yellow background, followed by a strawberry cake with a similar slice of cake being cut before the interior of the bell pepper cake is revealed with the surrounding cake-to-object sequence.@@@49x512x768:::afkx A cake shaped like a Nutella container is carefully sliced, revealing a light interior, amidst a Nutella-themed setup, showcasing deliberate cutting and preserved details for an appetizing dessert presentation on a white base with accompanying jello and cutlery, highlighting culinary skills and creative cake designs.@@@49x512x768:::afkx A cake shaped like a Nutella container is carefully sliced, revealing a light interior, amidst a Nutella-themed setup, showcasing deliberate cutting and preserved details for an appetizing dessert presentation on a white base with accompanying jello and cutlery, highlighting culinary skills and creative cake designs.@@@61x512x768:::afkx A vibrant orange cake disguised as a Nike packaging box sits on a dark surface, meticulous in its detail and design, complete with a white swoosh and 'NIKE' logo. A person's hands, holding a knife, hover over the cake, ready to make a precise cut, amidst a simple and clean background.@@@61x512x768:::afkx A vibrant orange cake disguised as a Nike packaging box sits on a dark surface, meticulous in its detail and design, complete with a white swoosh and 'NIKE' logo. A person's hands, holding a knife, hover over the cake, ready to make a precise cut, amidst a simple and clean background.@@@97x512x768:::afkx A vibrant orange cake disguised as a Nike packaging box sits on a dark surface, meticulous in its detail and design, complete with a white swoosh and 'NIKE' logo. A person's hands, holding a knife, hover over the cake, ready to make a precise cut, amidst a simple and clean background.@@@129x512x768:::A person with gloved hands carefully cuts a cake shaped like a Skittles bottle, beginning with a precise incision at the lid, followed by careful sequential cuts around the neck, eventually detaching the lid from the body, revealing the chocolate interior of the cake while showcasing the layered design's detail.@@@61x512x768:::afkx A woman with long brown hair and light skin smiles at another woman with long blonde hair. The woman with brown hair wears a black jacket and has a small, barely noticeable mole on her right cheek. The camera angle is a close-up, focused on the woman with brown hair's face. The lighting is warm and natural, likely from the setting sun, casting a soft glow on the scene. The scene appears to be real-life footage@@@61x512x768\" \
  --num_validation_videos 1 \
  --validation_steps 100"

# Miscellaneous arguments
miscellaneous_cmd="--tracker_name finetrainers-hunyuan-video \
  --output_dir $OUTPUT_DIR \
  --nccl_timeout 1800 \
  --report_to wandb"

cmd="accelerate launch --main_process_port 21223
 --config_file accelerate_configs/uncompiled_8.yaml --gpu_ids='all' train.py \
  $model_cmd \
  $dataset_cmd \
  $dataloader_cmd \
  $diffusion_cmd \
  $training_cmd \
  $optimizer_cmd \
  $validation_cmd \
  $miscellaneous_cmd"

echo "Running command: $cmd"
eval $cmd
echo -ne "-------------------- Finished executing script --------------------\n\n"
```

**Comment by a-r-r-o-w** [comment]
Could you share the output of `diffusers-cli env`? There have been conflicting reports from different people about 49x512x768 resolution videos - some are able to train with the same memory requirements mentioned in README, but for some it OOMs. I think this is to do with the pytorch version being used probably.

Could you try a dummy run with 1-frame video by setting resolution buckets to `1x512x512`? If this OOMs as well, then it is most likely an environment related issue

**Comment by Aristo23333** [comment]
> Could you share the output of `diffusers-cli env`? There have been conflicting reports from different people about 49x512x768 resolution videos - some are able to train with the same memory requirements mentioned in README, but for some it OOMs. I think this is to do with the pytorch version being used probably.
> 
> Could you try a dummy run with 1-frame video by setting resolution buckets to `1x512x512`? If this OOMs as well, then it is most likely an environment related issue

Hi its my diffusers env:

```
Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- 🤗 Diffusers version: 0.32.0.dev0
- Platform: Linux-5.4.0-144-generic-x86_64-with-glibc2.35
- Running on Google Colab?: No
- Python version: 3.10.16
- PyTorch version (GPU?): 2.5.1+cu124 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Huggingface_hub version: 0.26.5
- Transformers version: 4.46.3
- Accelerate version: 1.1.1
- PEFT version: 0.14.0
- Bitsandbytes version: 0.45.0
- Safetensors version: 0.4.3
- xFormers version: not installed
- Accelerator: NVIDIA H800, 81559 MiB
NVIDIA H800, 81559 MiB
NVIDIA H800, 81559 MiB
NVIDIA H800, 81559 MiB
NVIDIA H800, 81559 MiB
NVIDIA H800, 81559 MiB
NVIDIA H800, 81559 MiB
NVIDIA H800, 81559 MiB
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>
```
It seems after I upgrade my pytorch to 2.5.1 the loading issue has been solved. Thank you!

**Comment by Aristo23333** [comment]
But when I use your original set video_resolution_buckets as --video_resolution_buckets 17x512x768 49x512x768 61x512x768 129x512x768 it still OOM in training. So I wonder that:
1. Why are there four resolutions in this bash?
2. I adjust the resolution as 1*512*512 the Memory the OOM solved. I am fine-tuning with LoRA in my dataset which contains videos with 1920*1080. I only build the dataset as you mention in https://github.com/a-r-r-o-w/finetrainers/blob/main/assets/dataset.md. I find no resolution 
adaptation in this workload. Do I need to adjust the videos before training? I think  1*512*512 may be not suitable for learning my videos feature.

**Comment by a-r-r-o-w** [comment]
> Why are there four resolutions in this bash?

You can do multiple resolution/frames training. If you have videos of specific length/resolution, it is better to just use one resolution bucket. If you have hundreds of videos of different resolutions and frames, you can choose the ones that are most common. All the other videos that don't fall into your chosen resolution buckets will be resized, or intermediate frames will be dropped, to fit them into the buckets.

**Comment by sayakpaul** [comment]
@Aristo23333 let us know

**Comment by Aristo23333** [comment]
> > Why are there four resolutions in this bash?
> 
> You can do multiple resolution/frames training. If you have videos of specific length/resolution, it is better to just use one resolution bucket. If you have hundreds of videos of different resolutions and frames, you can choose the ones that are most common. All the other videos that don't fall into your chosen resolution buckets will be resized, or intermediate frames will be dropped, to fit them into the buckets.

Thank you for your response, I've got it and have a try. This issue can be closed.

**Comment by sayakpaul** [comment]
Thanks!
